DROP TABLE IF EXISTS SINGER_AUDIT;
DROP TABLE IF EXISTS SINGER_AUDIT_H;
DROP TABLE IF EXISTS REVINFO;
DROP TABLE IF EXISTS SINGER_INSTRUMENT ;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS SINGER;

CREATE TABLE SINGER_AUDIT (
    ID INT NOT NULL AUTO_INCREMENT,
    VERSION INT NOT NULL DEFAULT 0,
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    CREATED_BY VARCHAR(20),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(20),
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE UQ_SINGER_AUDIT (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID)
);
CREATE TABLE SINGER_AUDIT_H (
    ID INT NOT NULL AUTO_INCREMENT,
    VERSION INT NOT NULL DEFAULT 0,
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    CREATED_BY VARCHAR(20),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(20),
    LAST_MODIFIED_DATE TIMESTAMP,
    AUDIT_REVISION INT NOT NULL,
    ACTION_TYPE INT,
    AUDIT_REVISION_END INT,
    AUDIT_REVISION_END_TS TIMESTAMP,
    UNIQUE UQ_SINGER_AUDIT_H (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID, AUDIT_REVISION)
);
CREATE TABLE REVINFO (
    REVTSTMP BIGINT NOT NULL,
    REV INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (REVTSTMP, REV)
)
