CREATE TABLE SINGER (
    ID INT NOT NULL AUTO_INCREMENT,
    VERSION INT NOT NULL DEFAULT 0,
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    UNIQUE UQ_SINGER (FIRST_NAME, LAST_NAME),
    PRIMARY KEY (ID)
);

CREATE TABLE ALBUM (
    ID INT NOT NULL AUTO_INCREMENT,
    SINGER_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    VERSION INT NOT NULL DEFAULT 0,
    UNIQUE UQ_SINGER_ALBUM (SINGER_ID, TITLE),
    PRIMARY KEY (ID),
    CONSTRAINT FK_ALBUM_SINGER FOREIGN KEY (SINGER_ID) REFERENCES SINGER(ID)
);